[type/__postfix_postconf] Proper quoting of settings and values

diff --git a/type/__postfix_postconf/gencode-remote b/type/__postfix_postconf/gencode-remote
--- a/type/__postfix_postconf/gencode-remote
+++ b/type/__postfix_postconf/gencode-remote
@@ -2,6 +2,7 @@
 #
 # 2012-2014 Steven Armstrong (steven-cdist at armstrong.cc)
 # 2019 Nico Schottelius (nico-cdist at schottelius.org)
+# 2025 Dennis Camera (dennis.camera at riiengineerinh.ch)
 #
 # This file is part of the skonfig set __postfix.
 #
@@ -18,6 +19,12 @@
 # You should have received a copy of the GNU General Public License
 # along with this set. If not, see <http://www.gnu.org/licenses/>.
 #
+
+shquot() {
+	sed -e "s/'/'\\\\''/g" -e "1s/^/'/" -e "\$s/\$/'/" <<-EOF
+	$*
+	EOF
+}
 
 os=$(cat "${__global:?}/explorer/os")
 
@@ -59,11 +66,15 @@ value=$(cat "${__object:?}/parameter/value")
 
 case ${state_should}
 in
-   (absent)
-      # revert parameter to its default value
-      echo "postconf -# ${key}"
-      ;;
-   (present)
-      echo "postconf -e '${key}=${value}'"
-       ;;
+	(present)
+		printf 'postconf -e %s=%s\n' "$(shquot "${key}")" "$(shquot "${value}")"
+		;;
+	(absent)
+		# revert parameter to its default value
+		printf 'postconf -# %s\n' "$(shquot "${key}")"
+		;;
+	(*)
+		printf 'Invalid --state: %s\n' "${state_should}" >&2
+		exit 1
+		;;
 esac
